# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\tapp.proto\"\xcf\x02\n\x0bRequest_APP\x12\'\n\x05rtype\x18\x01 \x01(\x0e\x32\x18.Request_APP.RequestType\x12!\n\x05gtype\x18\x02 \x01(\x0e\x32\x12.Request_APP.GType\x12\x1b\n\x13status_modification\x18\x03 \x01(\t\x12#\n\x06on_off\x18\x04 \x01(\x0e\x32\x13.Request_APP.ON_OFF\x12\x0c\n\x04nome\x18\x05 \x01(\t\x12\n\n\x02ip\x18\x06 \x01(\t\x12\x0c\n\x04port\x18\x07 \x01(\x03\"$\n\x05GType\x12\x06\n\x02TV\x10\x00\x12\x06\n\x02\x41R\x10\x01\x12\x0b\n\x07LAMPADA\x10\x02\"I\n\x0bRequestType\x12\x0e\n\nReadStatus\x10\x00\x12\x0e\n\nReadSensor\x10\x01\x12\r\n\tModStatus\x10\x02\x12\x0b\n\x07ModOnOf\x10\x03\"\x19\n\x06ON_OFF\x12\x06\n\x02ON\x10\x00\x12\x07\n\x03OFF\x10\x01\":\n\x0cResponse_APP\x12\x13\n\x0bobject_name\x18\x01 \x01(\t\x12\x15\n\robject_result\x18\x02 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_REQUEST_APP_GTYPE = _descriptor.EnumDescriptor(
  name='GType',
  full_name='Request_APP.GType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TV', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LAMPADA', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=211,
  serialized_end=247,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_APP_GTYPE)

_REQUEST_APP_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='Request_APP.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ReadStatus', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ReadSensor', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ModStatus', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ModOnOf', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=249,
  serialized_end=322,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_APP_REQUESTTYPE)

_REQUEST_APP_ON_OFF = _descriptor.EnumDescriptor(
  name='ON_OFF',
  full_name='Request_APP.ON_OFF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ON', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OFF', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=324,
  serialized_end=349,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_APP_ON_OFF)


_REQUEST_APP = _descriptor.Descriptor(
  name='Request_APP',
  full_name='Request_APP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rtype', full_name='Request_APP.rtype', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gtype', full_name='Request_APP.gtype', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status_modification', full_name='Request_APP.status_modification', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='on_off', full_name='Request_APP.on_off', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nome', full_name='Request_APP.nome', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip', full_name='Request_APP.ip', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='Request_APP.port', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUEST_APP_GTYPE,
    _REQUEST_APP_REQUESTTYPE,
    _REQUEST_APP_ON_OFF,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=349,
)


_RESPONSE_APP = _descriptor.Descriptor(
  name='Response_APP',
  full_name='Response_APP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_name', full_name='Response_APP.object_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_result', full_name='Response_APP.object_result', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=409,
)

_REQUEST_APP.fields_by_name['rtype'].enum_type = _REQUEST_APP_REQUESTTYPE
_REQUEST_APP.fields_by_name['gtype'].enum_type = _REQUEST_APP_GTYPE
_REQUEST_APP.fields_by_name['on_off'].enum_type = _REQUEST_APP_ON_OFF
_REQUEST_APP_GTYPE.containing_type = _REQUEST_APP
_REQUEST_APP_REQUESTTYPE.containing_type = _REQUEST_APP
_REQUEST_APP_ON_OFF.containing_type = _REQUEST_APP
DESCRIPTOR.message_types_by_name['Request_APP'] = _REQUEST_APP
DESCRIPTOR.message_types_by_name['Response_APP'] = _RESPONSE_APP

Request_APP = _reflection.GeneratedProtocolMessageType('Request_APP', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST_APP,
  __module__ = 'app_pb2'
  # @@protoc_insertion_point(class_scope:Request_APP)
  ))
_sym_db.RegisterMessage(Request_APP)

Response_APP = _reflection.GeneratedProtocolMessageType('Response_APP', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE_APP,
  __module__ = 'app_pb2'
  # @@protoc_insertion_point(class_scope:Response_APP)
  ))
_sym_db.RegisterMessage(Response_APP)


# @@protoc_insertion_point(module_scope)
