# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\tapp.proto\"\xdb\x01\n\x07Request\x12#\n\x05rtype\x18\x01 \x01(\x0e\x32\x14.Request.RequestType\x12\x1d\n\x05gtype\x18\x02 \x01(\x0e\x32\x0e.Request.GType\x1a\x1d\n\x0cModifyStatus\x12\r\n\x05value\x18\x01 \x01(\x02\"/\n\x05GType\x12\t\n\x05GAMES\x10\x00\x12\x06\n\x02TV\x10\x01\x12\x06\n\x02\x41R\x10\x02\x12\x0b\n\x07LAMPADA\x10\x03\"<\n\x0bRequestType\x12\x0e\n\nReadStatus\x10\x00\x12\x0e\n\nReadSensor\x10\x01\x12\r\n\tModStatus\x10\x02\"\x89\x02\n\x08Response\x12$\n\x04type\x18\x01 \x01(\x0e\x32\x16.Response.ResponseType\x12\x1e\n\x05gtype\x18\x02 \x01(\x0e\x32\x0f.Response.GType\x1a\x1e\n\x06Sensor\x12\x14\n\x0csensor_value\x18\x01 \x01(\x02\x1a\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\t\x1a\x17\n\x03\x41\x64\x64\x12\x10\n\x08wellcome\x18\x01 \x01(\t\"3\n\x0cResponseType\x12\x0b\n\x07\x41\x64\x64User\x10\x00\x12\n\n\x06STATUS\x10\x01\x12\n\n\x06SENSOR\x10\x02\"/\n\x05GType\x12\t\n\x05GAMES\x10\x00\x12\x06\n\x02TV\x10\x01\x12\x06\n\x02\x41R\x10\x02\x12\x0b\n\x07LAMPADA\x10\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_REQUEST_GTYPE = _descriptor.EnumDescriptor(
  name='GType',
  full_name='Request.GType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GAMES', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TV', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AR', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LAMPADA', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=124,
  serialized_end=171,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_GTYPE)

_REQUEST_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='Request.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ReadStatus', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ReadSensor', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ModStatus', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=173,
  serialized_end=233,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_REQUESTTYPE)

_RESPONSE_RESPONSETYPE = _descriptor.EnumDescriptor(
  name='ResponseType',
  full_name='Response.ResponseType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AddUser', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SENSOR', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=401,
  serialized_end=452,
)
_sym_db.RegisterEnumDescriptor(_RESPONSE_RESPONSETYPE)

_RESPONSE_GTYPE = _descriptor.EnumDescriptor(
  name='GType',
  full_name='Response.GType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GAMES', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TV', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AR', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LAMPADA', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=124,
  serialized_end=171,
)
_sym_db.RegisterEnumDescriptor(_RESPONSE_GTYPE)


_REQUEST_MODIFYSTATUS = _descriptor.Descriptor(
  name='ModifyStatus',
  full_name='Request.ModifyStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Request.ModifyStatus.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=122,
)

_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rtype', full_name='Request.rtype', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gtype', full_name='Request.gtype', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_REQUEST_MODIFYSTATUS, ],
  enum_types=[
    _REQUEST_GTYPE,
    _REQUEST_REQUESTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=233,
)


_RESPONSE_SENSOR = _descriptor.Descriptor(
  name='Sensor',
  full_name='Response.Sensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor_value', full_name='Response.Sensor.sensor_value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=348,
)

_RESPONSE_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='Response.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='Response.Status.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=374,
)

_RESPONSE_ADD = _descriptor.Descriptor(
  name='Add',
  full_name='Response.Add',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wellcome', full_name='Response.Add.wellcome', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=399,
)

_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Response.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gtype', full_name='Response.gtype', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RESPONSE_SENSOR, _RESPONSE_STATUS, _RESPONSE_ADD, ],
  enum_types=[
    _RESPONSE_RESPONSETYPE,
    _RESPONSE_GTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=501,
)

_REQUEST_MODIFYSTATUS.containing_type = _REQUEST
_REQUEST.fields_by_name['rtype'].enum_type = _REQUEST_REQUESTTYPE
_REQUEST.fields_by_name['gtype'].enum_type = _REQUEST_GTYPE
_REQUEST_GTYPE.containing_type = _REQUEST
_REQUEST_REQUESTTYPE.containing_type = _REQUEST
_RESPONSE_SENSOR.containing_type = _RESPONSE
_RESPONSE_STATUS.containing_type = _RESPONSE
_RESPONSE_ADD.containing_type = _RESPONSE
_RESPONSE.fields_by_name['type'].enum_type = _RESPONSE_RESPONSETYPE
_RESPONSE.fields_by_name['gtype'].enum_type = _RESPONSE_GTYPE
_RESPONSE_RESPONSETYPE.containing_type = _RESPONSE
_RESPONSE_GTYPE.containing_type = _RESPONSE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(

  ModifyStatus = _reflection.GeneratedProtocolMessageType('ModifyStatus', (_message.Message,), dict(
    DESCRIPTOR = _REQUEST_MODIFYSTATUS,
    __module__ = 'app_pb2'
    # @@protoc_insertion_point(class_scope:Request.ModifyStatus)
    ))
  ,
  DESCRIPTOR = _REQUEST,
  __module__ = 'app_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  ))
_sym_db.RegisterMessage(Request)
_sym_db.RegisterMessage(Request.ModifyStatus)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(

  Sensor = _reflection.GeneratedProtocolMessageType('Sensor', (_message.Message,), dict(
    DESCRIPTOR = _RESPONSE_SENSOR,
    __module__ = 'app_pb2'
    # @@protoc_insertion_point(class_scope:Response.Sensor)
    ))
  ,

  Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
    DESCRIPTOR = _RESPONSE_STATUS,
    __module__ = 'app_pb2'
    # @@protoc_insertion_point(class_scope:Response.Status)
    ))
  ,

  Add = _reflection.GeneratedProtocolMessageType('Add', (_message.Message,), dict(
    DESCRIPTOR = _RESPONSE_ADD,
    __module__ = 'app_pb2'
    # @@protoc_insertion_point(class_scope:Response.Add)
    ))
  ,
  DESCRIPTOR = _RESPONSE,
  __module__ = 'app_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  ))
_sym_db.RegisterMessage(Response)
_sym_db.RegisterMessage(Response.Sensor)
_sym_db.RegisterMessage(Response.Status)
_sym_db.RegisterMessage(Response.Add)


# @@protoc_insertion_point(module_scope)
