# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculadora.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculadora.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x63\x61lculadora.proto\">\n\x0bRequestCalc\x12\r\n\x05num_1\x18\x01 \x01(\x02\x12\r\n\x05num_2\x18\x02 \x01(\x02\x12\x11\n\toperation\x18\x03 \x01(\x05\"\x1d\n\x0cResponseCalc\x12\r\n\x05value\x18\x01 \x01(\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REQUESTCALC = _descriptor.Descriptor(
  name='RequestCalc',
  full_name='RequestCalc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_1', full_name='RequestCalc.num_1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_2', full_name='RequestCalc.num_2', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operation', full_name='RequestCalc.operation', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=83,
)


_RESPONSECALC = _descriptor.Descriptor(
  name='ResponseCalc',
  full_name='ResponseCalc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='ResponseCalc.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['RequestCalc'] = _REQUESTCALC
DESCRIPTOR.message_types_by_name['ResponseCalc'] = _RESPONSECALC

RequestCalc = _reflection.GeneratedProtocolMessageType('RequestCalc', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTCALC,
  __module__ = 'calculadora_pb2'
  # @@protoc_insertion_point(class_scope:RequestCalc)
  ))
_sym_db.RegisterMessage(RequestCalc)

ResponseCalc = _reflection.GeneratedProtocolMessageType('ResponseCalc', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSECALC,
  __module__ = 'calculadora_pb2'
  # @@protoc_insertion_point(class_scope:ResponseCalc)
  ))
_sym_db.RegisterMessage(ResponseCalc)


# @@protoc_insertion_point(module_scope)
