# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HAmsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='HAmsg.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0bHAmsg.proto\" \n\x0cHAFromSensor\x12\x10\n\x08variable\x18\x01 \x01(\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HAFROMSENSOR = _descriptor.Descriptor(
  name='HAFromSensor',
  full_name='HAFromSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='variable', full_name='HAFromSensor.variable', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=47,
)

DESCRIPTOR.message_types_by_name['HAFromSensor'] = _HAFROMSENSOR

HAFromSensor = _reflection.GeneratedProtocolMessageType('HAFromSensor', (_message.Message,), dict(
  DESCRIPTOR = _HAFROMSENSOR,
  __module__ = 'HAmsg_pb2'
  # @@protoc_insertion_point(class_scope:HAFromSensor)
  ))
_sym_db.RegisterMessage(HAFromSensor)


# @@protoc_insertion_point(module_scope)
